"""empty message

Revision ID: 717d3b1de814
Revises: 
Create Date: 2024-01-22 10:06:34.347514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717d3b1de814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('added', sa.DateTime(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_to', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message_from', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('message_from')
        batch_op.drop_column('message_to')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('added')
        batch_op.drop_column('total')

    # ### end Alembic commands ###
