"""empty message

Revision ID: b54d0e85e719
Revises: ee3df9d4d5ad
Create Date: 2024-01-29 10:04:28.537941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54d0e85e719'
down_revision = 'ee3df9d4d5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('listing', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('transactionId', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('count', sa.Boolean(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appId', sa.String(), nullable=True),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('packageId', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('charges', sa.Float(), nullable=True),
    sa.Column('balanceBefore', sa.Float(), nullable=True),
    sa.Column('balanceAfter', sa.Float(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('requested', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('transactionType', sa.String(), nullable=True),
    sa.Column('ledgerEntryId', sa.Integer(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('prestoTransactionId', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('telegramChatId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('package')
    op.drop_table('ledger_entry')
    # ### end Alembic commands ###
