"""empty message

Revision ID: ee3df9d4d5ad
Revises: 09d443dc74f8
Create Date: 2024-01-24 09:36:45.000670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3df9d4d5ad'
down_revision = '09d443dc74f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('groupName', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('groupId', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('groupId')
        batch_op.drop_column('groupName')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
